### ISSUE TITLE
livewire support ?

### ISSUE THREAD

**Issue by tolyod** [abbasudo/laravel-purity#11]
due to the fact that the library is closely tied to the `request()` that's listed in 

[Filterable.php#L42](https://github.com/abbasudo/laravel-purity/blob/a739073cca4f6ce72f16b2c5dee3d9a909d1e607/src/Traits/Filterable.php#L42)

is there any chance or possibility to use it together with Livewire ?

**Comment by tolyod** [comment]
@abbasudo  
expressed my proposal in a [pull request](https://github.com/abbasudo/laravel-purity/pull/13)

**Comment by abbasudo** [comment]
@tolyod
great job thanks. I'll do some refactors before merging it.

**Comment by abbasudo** [comment]
thanks to @tolyod for making #17.
this feature has been added to the package at https://github.com/abbasudo/laravel-purity/releases/tag/v2.0.0.
