### ISSUE TITLE
Ability to validate/specify filterable fields

### ISSUE THREAD

**Issue by ItsReddi** [abbasudo/laravel-purity#12]
Hello,
thanks for this package i am currently trying it out.

Maybe i miss some point, but how we can **restrict and validate** the fields / values that should be available for filtering, sorting and so on?
More than that it seems not to check if the field is generally available for eloquent.

For example:
`{{baseUrl}}/tasks?filters[doesnotexist][$eq]=1`, will end in a QueryException.

**Comment by abbasudo** [comment]
hello,
im glad that this package helped you.

restrict and validating fields are in the package roadmap and will be ready in a few days.
QueryException will be avoided by validating the fields first. so stay tuned for the next update.

**Comment by abbasudo** [comment]
as said in #6 this feature has been added to the package.
read more in [docs](https://github.com/abbasudo/laravel-purity#allowed-fields)

**Comment by ItsReddi** [comment]
Great job, thank you.
I read the Docs and Code, but i cannot find the way to validate the inputs. It seems that only restriction of fields is added.
Am i correct?

I think it is not an issue, since we could validate the requests before getting to sort / filter.

And than maybe use $request->validated() if available?

**Comment by abbasudo** [comment]
i have added field validation. any field except the one specified in the model will be rejected or ignored (depending on the config).
however, validating values is beyond the scope of purity.

if you want to validate values you can use requests validate to validate. if there is any validation error it will return 422. otherwise, it will run normally.
```php
    public function index(Request $request)
    {
        $request->validate([
            'filters.email.$eq' => 'sometimes|string',
            'filters.id.$in'    => 'required|array|exists:users,id'
        ]);

        $users = User::with('profile')->filter()->latest()->get();

        return (UserResource::collection($users))->response()->setStatusCode(
            Response::HTTP_OK
        );
    }
```
