### ISSUE TITLE
Sort by relation fields needed

### ISSUE THREAD

**Issue by a1exts** [abbasudo/laravel-purity#22]
Also need sort by relation fields as filtering

**Comment by abbasudo** [comment]
that feature is a little bit complex to implement however it is on the roadmap of purity.

**Comment by abbasudo** [comment]
any PR to implement this feature will be accepted.

**Comment by olivierbaudouin** [comment]
Any news about this important feature?

**Comment by LostDok** [comment]
Also need this feature a lot. Thank you!
