### ISSUE TITLE
feature request : ability to limit operator per field

### ISSUE THREAD

**Issue by DJafari** [abbasudo/laravel-purity#29]
Is it possible to limit operators per field of the model?

For example, I want to restrict the use of `$eq` and `$contains` operators only for the `User.name` field.

**Comment by abbasudo** [comment]
@DJafari Currently there is no such feature. any contribution to add this feature would be accepted.

**Comment by abbasudo** [comment]
this feature have been added to the package in #31 
you can read more about it in the documents in this [link](https://github.com/abbasudo/laravel-purity?tab=readme-ov-file#restrict-filters-by-field)
