### ISSUE TITLE
Mistake on complex filtering example in doc?

### ISSUE THREAD

**Issue by olivierbaudouin** [abbasudo/laravel-purity#37]
I think that there a mistake on [Complex Filtering Example](https://github.com/abbasudo/laravel-purity#complex-filtering)

Expected: "Find books with 2 possible dates and a specific author"
But result for me is: "Find books with 2 possible dates OR a specific author" 

Or, with my own example below (filtering on User model): 

Expected: "Find users with username containing 'mi' or 'E' and in "Bureau" department"
Result: "Find users with username containing 'mi' or 'E' OR in "Bureau" department"

To obtain expected result:

```js
const filters = {
  $and: [
    {
      $or: [
        {username: {$contains: 'mi'}},
        {
          username: {$contains: 'E'}
        }
      ]
    },
    {
      'department': {
        name: {$eq: 'Bureau'}
      }
    }
  ]
}
```

**Comment by abbasudo** [comment]
hello @olivierbaudouin. that's true, however, the documentation is correct. the expected behavior when no operator passed is `$and` you don't have to specify it explicitly. clearly, there is an issue with the resolver of the package. Any PR to fix that is welcome.

**Comment by Lakshan-Madushanka** [comment]
I think it is a logical grouping(brackets)  issue. 

Expected Query:  ('mi' or 'E') **and** (in "Bureau" department")
Result Query: "'mi' or 'E' and in "Bureau" department"

So accordingly operator precedence SQL find the results for mi **or** (E and in Bureau).

I speculate package is not designed to group using or operator as below.
('mi' or 'E') **or** (in "Bureau" department")

@abbasudo If that possible what should be the query string ?
