### ISSUE TITLE
Changes needed in relation sorting

### ISSUE THREAD

**Issue by abbasudo** [abbasudo/laravel-purity#57]
Sorting relations implemented properly so far. However, there are some tasks that are needed to be done at this point.

- [ ] ~~Sorting should be separating fields and relations by brackets just like filtering as its purity convention. it is currently separating those by dot. For example `/posts?sort[user][name]=asc`~~
- [ ] Documentation should be updated. 
- [ ] Nested relation sort support needed.

**Comment by abbasudo** [comment]
@Lakshan-Madushanka we can ignore nested relation sort due to its complexity. Please write a documentation section for sorting relations and resolve #22.

**Comment by Lakshan-Madushanka** [comment]
@abbasudo "I agree with you. Implementing one-level relationship sorting wasn't as easy as it seemed; it took time. However, it's not just about complexity. Practically, most of the time, we need to sort records by a column of the related table itself and sometimes by a column of the related table. But in my experience, sorting by nested relationships rarely occurs.

We don't need to blindly implement every possible feature unless users really need it.

**Comment by Lakshan-Madushanka** [comment]
I'll update the related documentation.

**Comment by abbasudo** [comment]
@Lakshan-Madushanka Thanks.
