### ISSUE TITLE
Renamed Filters overwrite the Available Filters

### ISSUE THREAD

**Issue by Lakshan-Madushanka** [abbasudo/laravel-purity#63]
[Here](https://github.com/abbasudo/laravel-purity/blob/5dc70b98c6548e56a175c9702566e86962354b51/src/Traits/Filterable.php#L141C26-L141C45), we should not give priority to $renamedFilters if $availableFilters are defined.

**Comment by abbasudo** [comment]
Hi @Lakshan-Madushanka Thanks for reviewing #60 and finding this bug.
