### ISSUE TITLE
problem with relational filtering

### ISSUE THREAD

**Issue by hosseinjarrahi** [abbasudo/laravel-purity#67]
hi, i have this model

```php
<?php

namespace Modules\Content\Models;

use App\Models\Base;
use Modules\Common\Models\Rate;
use Modules\Common\Traits\HasCategory;

class ContentProvider extends Base
{
    use HasCategory;

    protected $guarded = ['id'];

    public function contents()
    {
        return $this->hasMany(Content::class);
    }

    public function rates()
    {
        return $this->hasManyThrough(Rate::class, Content::class);
    }
}
```
my Base Class is
```php
<?php

namespace App\Models;

use Abbasudo\Purity\Traits\Sortable;
use Abbasudo\Purity\Traits\Filterable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Haruncpi\LaravelUserActivity\Traits\Loggable;


class Base extends Model
{
    use Loggable, SoftDeletes, Filterable, Sortable;

```

when i filter using this filter query ```filters[categories][name][$eq]=test``` in Resolve Class i found this validateField function

```php
private function validateField(string $field): void
    {
        $availableFields = $this->model->availableFields();

        if (!in_array($field, $availableFields)) {
            throw FieldNotSupported::create($field, $this->model::class, $availableFields);
        }
    }
```

i have rates and contents and categories relation but validate field failed because it is not in availableFields

available fields is there
```php
array (
  0 => 'created_at',
  1 => 'deleted_at',
  2 => 'id',
  3 => 'name',
  4 => 'title_to',
  5 => 'updated_at',
  6 => 'content_providers.created_at',
  7 => 'content_providers.deleted_at',
  8 => 'content_providers.id',
  9 => 'content_providers.name',
  10 => 'content_providers.title_to',
  11 => 'content_providers.updated_at',
)  
```

how i can fix this, so i need add something in model or not?

**Comment by abbasudo** [comment]
Hey @hosseinjarrahi .
Each model has to have a `$availableFields` array corresponding to itself.

**Comment by AhmedMedDev** [comment]
@hosseinjarrahi 

the relations should be strictly type https://github.com/abbasudo/laravel-purity/pull/66

``
    public function contents() : HasMany
    {
        return $this->hasMany(Content::class);
    }

    public function rates(): HasManyThrough
    {
        return $this->hasManyThrough(Rate::class, Content::class);
    }
  ``

**Comment by hosseinjarrahi** [comment]
thanx @AhmedMedDev And  @abbasudo ; my problem solved by @AhmedMedDev  answer. ❤️
