### ISSUE TITLE
Filter for element of json column

### ISSUE THREAD

**Issue by datenzalat** [abbasudo/laravel-purity#8]
Hello out there, this package saves my ass after first trying to build a quick solution myself. But this one takes the cake, just great!
I just have a quick question that I didn't find in the docs or I'm up the creek.

I would like to call `/items?filters[tags][$in]=1` while in my items table there is a column "tags" of type json, e.g. `[1, 5, 6]`.
Laravel offers the JSON Where Clauses since 5.5. But how to do that with purity?

**Comment by abbasudo** [comment]
Hello @datenzalat, glad to hear that Purity helped you.
purity doesn't support `whereJsonContains` at the moment however you can add custom filters to your project. follow the instruction in this [link](https://abbasudo.github.io/laravel-purity/#custom-filters) to create a custom filter class then add the following code : 
```php
class JsonFilter extends Filter
{
    /**
     * Operator to detect in the query params.
     *
     * @var string
     */
    protected static string $operator = '$json';

    /**
     * Apply filter logic to $query.
     *
     * @return Closure
     */
    public function apply(): Closure
    {
        return function ($query) {
            $query->whereJsonContains($this->column, $this->values);
        };
    }
}
```
and filter the data by this query: `/items?filters[tags][$json][0]=1`
I didn't test this implementation however it will do the job. please give me feedback so I can add it to the main package.

**Comment by datenzalat** [comment]
Did it with a custom filter
`return function (Builder $query) {
	foreach ($this->values as $value) {
		$query->whereRaw('JSON_CONTAINS(' . $this->column . ', "' . $value . '")');
	}
};`

no idea, if there is a better way
