### ISSUE TITLE
ContainsFilter case insensitive fails when using PostgreSQL

### ISSUE THREAD

**Issue by carlos-talavera** [abbasudo/laravel-purity#82]
I migrated a project I'm currently working on from MySQL to PostgreSQL and noticed that my search filters were broke, they became case sensitive all of a sudden. After some investigation I saw that the filter `$contains` uses "LIKE", which in PostgreSQL, unlike MySQL, isn't case insensitive. This is the current filter

```php
<?php

namespace Abbasudo\Purity\Filters\Strategies;

use Abbasudo\Purity\Filters\Filter;
use Closure;

class ContainsFilter extends Filter
{
    /**
     * Operator string to detect in the query params.
     *
     * @var string
     */
    protected static string $operator = '$contains';

    /**
     * Apply filter logic to $query.
     *
     * @return Closure
     */
    public function apply(): Closure
    {
        return function ($query) {
            foreach ($this->values as $value) {
                $query->where($this->column, 'like', "%{$value}%");
            }
        };
    }
}
```

A solution for this is to use `ILIKE` instead of `LIKE` to make it work with PostgreSQL. Like this:

```php
$query->where($this->column, 'ilike', "%{$value}%");
```

On my current project, I just created my own ContainsFilter and replaced the library's one with it, using `ILIKE` instead of `LIKE`. I think it's something worth checking out.

**Comment by rdizio** [comment]
This needs a switch case by the database driver used because each database has a different behavior. I think it was already fix in the master branch, but we might be waiting for some test to pass.

**Comment by carlos-talavera** [comment]
Yeah, just submitted the PR #84 with the fix for several DB drivers. The changes that you mentioned were implemented on the ContainsSensitiveFilter, but the ContainsFilter was still missing the fix.

**Comment by abbasudo** [comment]
@carlos-talavera Thank you for your contribution! i just drafted a new version [v3.3.4](https://github.com/abbasudo/laravel-purity/releases/tag/v3.3.4) with the changes you've implemented.

**Comment by carlos-talavera** [comment]
Thank you! Awesome library! I'm happy to do my bit :)
