### ISSUE TITLE
Access to undeclared static property Filter::$operator

### ISSUE THREAD

**Issue by exonos** [abbasudo/laravel-purity#9]
Hello! your package is quite simple and powerful, i read your documentation and i can't use this, the package is functional but when i filter by this ?filters[id][$in][0]=3 i get the error **Access to static property undeclared Filter::$operator** seems like $operator doesn't find the class correctly, I debug line by line with dd but it still doesn't work. can you provide more information about this error?

**Comment by abbasudo** [comment]
Hello! I'm glad to hear that you find the package powerful. Based on the error you provided, you have created a filter class that doesn't have an operator property. each custom filter class should have a static $operator variable.

thanks again for your compliment and have a good day.
